### ISSUE TITLE
not hooked to some applications

### ISSUE THREAD

**Issue by jkowalleck** [w0lfschild/winBuddy#1]
works fine for most applications. Border is drawn, window menu is added.
But in some apps nothing happened. No border, no window menu hook. Example: Apple Calendar, Apple Mail.

**Comment by w0lfschild** [comment]
Sounds like a mySIMBL issue. Is anything being injected at all?

**Comment by jkowalleck** [comment]
What do you mean by "anything injected at all"?

**Comment by w0lfschild** [comment]
When you open an application with winBuddy active you should get two messages in console:

`Loading winBuddy...`
`winBuddy loaded into <bundleID> on macOS 10.12`

If you're not seeing those then it's not even being loaded and the issue has nothing to do with winBuddy.

**Comment by jkowalleck** [comment]
watched the console. 
some entries appear, like "default	13:53:52.603301 +0100	Console	winBuddy loaded into com.apple.Console on macOS 10.12"
No log for Apple Mail, Apple Calendar.

at which place should i open an issue, to get this fixed?

**Comment by w0lfschild** [comment]
Hmm probably a mySIMBL issue. Do other plugins load into those applications automatically? Would need to know more about your system.

**Comment by w0lfschild** [comment]
Is it possible you have those applications blacklisted in mySIMBL?

**Comment by wwdc17** [comment]
Hey @w0lfschild, don't mean to bump an old issue, but all SIMBL plugins haven't been loading into Safari for me for a while now... looks like others also have this problem. Any steps I could take to fix this?

**Comment by w0lfschild** [comment]
@wwdc17 https://github.com/anakinsk/SafariStand/issues/38#issuecomment-289665394

**Comment by wwdc17** [comment]
Woah is that safe?? Any way to just make it use SafariWebKitDev automatically?
