### ISSUE TITLE
Draw a new title bar entirely?

### ISSUE THREAD

**Issue by sealevelcain** [w0lfschild/winBuddy#22]
Would it be possible for winbuddy to draw a new title bar over the existing one, acting as a sort of shell or overlay? If this is possible I think it could allow for some cool theming capabilities. Access to the traffic lights isn't entirely necessary as this can be managed with keyboard shortcuts. 

As far as I can tell this is semi-possible with the menu bar as the app Vanilla (app similar to bartender) seems to put an image over your menubar to hide the icons  - something I noticed after it bugged out and obscured the window/help menus.

**Comment by w0lfschild** [comment]
Sounds way too complex.

**Comment by sealevelcain** [comment]
Fair enough!
