### ISSUE TITLE
No winBuddy in window menu on Mojave

### ISSUE THREAD

**Issue by hrytskivr** [w0lfschild/winBuddy#29]
I was trying to use your great tool today on MacOS Mojave and after installing, allowing permissions, restarting apps & even laptop there was no winBuddy  section under window.

**Comment by hrytskivr** [comment]
Yes I do

**Comment by WatermelonDriveway** [comment]
@hrytskivr is this still an issue? Winbuddy is my last thing to check off on my "will it still work on Mojave" list before I upgrade.

**Comment by RealAndiB** [comment]
@WatermelonDriveway 
Yes, unfortunately it is...

**Comment by hrytskivr** [comment]
Closing as I don't longer have Mojave thus unable to test and provide any details. Cheers.
