### ISSUE TITLE
Disable border in fullscreen

### ISSUE THREAD

**Issue by net** [w0lfschild/winBuddy#4]
It would be nice if the border was disabled in fullscreen applications and in fullscreen Chrome video. Could this be done by adding to the blacklists?

**Comment by w0lfschild** [comment]
Hmm yeah that's more like a bug than something that should be blacklisted.

**Comment by net** [comment]
Related: border shows on the volume indicator and in the Today pane in the notification center.

**Comment by w0lfschild** [comment]
Okay the issue with Notification Center is fixed in the latest version as well as automatically hiding the border when an application goes full screen.

0.2.8 should be available on mySIMBL now.

**Comment by net** [comment]
Awesome, thanks!
