### ISSUE TITLE
Bug: Also applies to volume, brightness, and key brightness HUDs.

### ISSUE THREAD

**Issue by wwdc17** [w0lfschild/winBuddy#6]
It currently applies that ass ugly (sorry) border to the volume, brightness, and other "center" "squares" in macOS (Sierra). Could this be fixed? On a related note, could we have the possibility to set the default to have no shadow, but no border?

Thanks

**Comment by w0lfschild** [comment]
This should be fixed in [0.3.1](https://github.com/w0lfschild/myRepo/blob/master/mytweaks/bundles/winBuddy_0.3.1.zip)

**Comment by wwdc17** [comment]
Awesome, thanks!
