### ISSUE TITLE
bug: winbuddy breaks system preferences when enabled

### ISSUE THREAD

**Issue by jeremiahwright** [w0lfschild/winBuddy#8]
i just upgraded to 10.12.4

when winbuddy is enabled in mysimbl, whenever i try to access a system preferences pane (general for example) i get a pop up "preferences error" and the general pane does not load. this happens with almost all the panes (exception is desktop & screensaver)

when I disabled winbuddy in mysimbl the system preferences work again, so I am pretty sure this has to do with winbuddy

**Comment by jeremiahwright** [comment]
@w0lfschild

**Comment by w0lfschild** [comment]
This should be fixed in [0.3.1](https://github.com/w0lfschild/myRepo/blob/master/mytweaks/bundles/winBuddy_0.3.1.zip)

**Comment by jeremiahwright** [comment]
Thanks for your reply. I am noticing the same problem in some apps (Microsoft Office, Acrobat, PDF Expert, etc.) when I use the "Save As" dialog or "Open" dialog in the apps the file window crashes. When I disable winbuddy it works. Are you able to reproduce this bug?


On Apr 1, 2017, at 12:36 AM, Wolfgang Baird <notifications@github.com> wrote:

This should be fixed in 0.3.1 <https://github.com/w0lfschild/myRepo/blob/master/mytweaks/bundles/winBuddy_0.3.1.zip>
